version: "3"
services:
  app:
    container_name: pxeboot
    image: ajtak/pxeboot:latest
    ports:
      - "53:53"

    environment:
      - NFS_PATH="192.168.0.150:/srv/storage/"
      #ports:
    #  - "4000:80"
    #networks:
    #  - webnet
  #networks:
  #webnet:
